<a href="https://colab.research.google.com/github/Jamesvh12346/Jamesvh12346.github.io/blob/main/pmtrackerscraper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
pip install tabula-py

Requirement already satisfied: tabula-py in /usr/local/lib/python3.7/dist-packages (2.3.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.19.5)
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.1.5)
Requirement already satisfied: distro in /usr/local/lib/python3.7/dist-packages (from tabula-py) (1.6.0)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2018.9)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.25.3->tabula-py) (1.15.0)

In [18]:
import tabula

In [19]:
file1 = "https://docs.cdn.yougov.com/yx9dysl1ym/YG%20trackers%20-%20Best%20Prime%20Minister_W.pdf"

In [24]:
table = tabula.read_pdf(file1,pages=1)

In [21]:
table[0]

             Unnamed: 0         Unnamed: 1  ... Refused Johnson\rLead
0                   NaN                NaN  ...       %             %
1   Start of\rFieldwork  End of\rFieldwork  ...     NaN           NaN
2                  2021                NaN  ...     NaN           NaN
3            19/12/2021         20/12/2021  ...       5           -12
4            14/12/2021         15/12/2021  ...       4           -10
5            01/12/2021         02/12/2021  ...       4            -4
6            24/11/2021         25/11/2021  ...       3            -1
7            17/11/2021         18/11/2021  ...       5            -2
8            10/11/2021         11/11/2021  ...       3            -2
9            12/10/2021         13/10/2021  ...       3             6
10           15/09/2021         16/09/2021  ...       5             5
11           02/09/2021         03/09/2021  ...       5             5
12           25/08/2021         26/08/2021  ...       4             5
13           11/08/2021         12/08/2021  ...       3             2
14           05/08/2021         06/08/2021  ...       5             4
15           28/07/2021         29/07/2021  ...       3             5
16           15/07/2021         16/07/2021  ...       5            10
17           07/07/2021         08/07/2021  ...       5             8
18           29/06/2021         30/06/2021  ...       4             6
19           16/06/2021         17/06/2021  ...       5            10
20           09/06/2021         10/06/2021  ...       5             9
21           27/05/2021         28/05/2021  ...       3            12
22           19/05/2021         20/05/2021  ...       4            16
23           13/04/2021         14/04/2021  ...       4             8
24           07/04/2021         08/04/2021  ...       4             6
25           31/03/2021         01/04/2021  ...       3             6
26           25/03/2021         26/03/2021  ...       2            10
27           18/03/2021         19/03/2021  ...       3             6
28           09/03/2021         10/03/2021  ...       3             5
29           03/03/2021         04/03/2021  ...       2             8
30           25/02/2021         26/02/2021  ...       3             4
31           17/02/2021         18/02/2021  ...       4             4
32           09/02/2021         10/02/2021  ...       2             2
33           02/02/2021         03/02/2021  ...       4             0
34           26/01/2021         27/01/2021  ...       4            -5
35           21/01/2021         22/01/2021  ...       4            -2
36           13/01/2021         14/01/2021  ...       3            -5
37           04/01/2021         05/01/2021  ...       3            -5
38                 2020                NaN  ...     NaN           NaN
39           15/12/2020         16/12/2020  ...       2            -5
40           08/12/2020         09/12/2020  ...       3            -4

[41 rows x 7 columns]

In [27]:
tabula.convert_into("https://docs.cdn.yougov.com/yx9dysl1ym/YG%20trackers%20-%20Best%20Prime%20Minister_W.pdf", "pmtracker.csv")

'pages' argument isn't specified.Will extract only from page 1 by default.